### ISSUE TITLE
Bugreport: Map-view never receives AttributeEvents automatically anymore after being once offline

### ISSUE THREAD

**Issue by peterdewitte** [openremote/openremote#1200]
---
name: Bug report
title: 'Map-view never receives AttributeEvents automatically anymore after being once offline'
labels: ''
assignees: ''

---
**Describe the bug**
The map view stays static after being offline once. You can reproduce the issue on all platforms, app, mobile browsers, desktop environments, ...

I have a use case and an example for this bug:

I made an alarm system for assets that are moving. For the sake of clarity let's take the *Hotel New York* ship in the online demo. If something is wrong, I send out a Firebase notification to the customer in the app. The customer opens up the app to see that nothing is wrong on the map. The assets are shown in the same location as the last usage of the app. Also, the alarm colours are not shown. If the app hasn't been used for a while, the app goes through a cycle passing the *offline* page. If the map view has been through an offline cycle even once, it no longer receives any AttributeEvents. No AttributeEvents are shown made while offline, nor new AttribuesEvents are ever shown. The page is now a static map. It can be resolved by manually reloading the map.

In the second use-case, I return to Sollingen, the event where we had a nice chat last month. Again, thank you for your hospitality. I noticed some engineers were continuously monitoring the map of the car demo. The website was reloaded manually because something was wrong with the cars. It is none of my business to tell you what is going wrong, but the router on the event had a bad 4G connection, and the demo went through offline cycles continuously. Reloading the map manually always solves the issue.

Note I can break the map view with an offline cycle, but the asset tree view does the job well. Afterwards, it still receives AttributeEvents. The asset view sometimes does a full *reconnect* after being offline, which solves for sure the isssue.

**To Reproduce**

The location and course of the ship *Hotel New York*, updates every 5 minutes sharp on the minutes 0, 5, 10, 15, ... This is called from now on a 5-minute mark.

Steps to reproduce the behaviour:
1. Open the online openremote demo on the smart city realm. Put it on the map view and look for the ship.
2. Take a screenshot of the ship or remember the position. 
3. Remove the internet from your device. Go into airplane mode. Make sure you see the offline page.
4. Wait and make sure you have passed a 5-minute mark. You are now sure the boat has been moved.
5. Restore the connection
6. Compare the current map with your screenshot, *Hotel New York* has not been repositioned on the map. If you check it on a separate device, it did.
6. Wait for the next 5-minute mark. *Hotel New York* should have been repositioned, but the map view has not received any update. *Hotel New York* stays forever in the position it had just before going offline.

**Expected behaviour**
Restoring the connection after the offline page should also restore the ability to receive AttributeEvents in the map view

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version:12.0.1

**Smartphone (please complete the following information):**
 - Device: Galaxy s10e
 - OS: Android 12
 - Browser Chrome
 - Version: 119.0.

**Additional context**
The app always starts from an offline state. When you open the app and land on the map, the data displayed is untrustworthy. You need to reload the map manually always.

**Comment by MartinaeyNL** [comment]
Thanks for clearly describing the issue!

You indeed reference to Solingen where we were already aware of the issue.
I've already been busy for weeks fixing it, but it's quite a complicated one,
especially when you take consoles into count.  So I'm on it! haha

I'll take this case into count, and let you know when a fix is merged :)

**Comment by peterdewitte** [comment]
Ok

That is great. 

As an engineer, I was aware that something was off in Solingen, as I have the mindset as well on how to keep something working during product demos. I only noticed that every one of you had to show first some assets in the asset tree before showing something else. But I could not pinpoint the exact reason for that behaviour. It is also an edge case you only get to know when you hit the road with your product. Anyhow, you did a great job. And the product is stable enough to survive these types of oddities. I have chosen to evaluate your product based on the activity and community found over here. You will fix it. A project is a living thing.

I can imagine it is a hard nut to crack. A break in connection leaves you in an unknown state. 

I have one question left. In the issue template, we are asked not to report an issue if you are not a developer. So, until now, I did not. I noticed I raised bugs in on the forum hat are being replicated over here weeks later. Can I keep posting my bug reports over here?

Best regards

Peter

**Comment by MartinaeyNL** [comment]
Nothing wrong with posting an issue here 👍 
We just try to avoid non-technical issues which we redirect to the forum instead.

However, the amount of issues we have pending is quite large, and since GitHub isn't "great" at sending notifications,
some issues might get lost over time. Might be worth creating a GitHub issue, making a forum post including the link,
so we (and other community members) become aware of it 😉 

Feel free to do anything, we appreciate input like this!

**Comment by peterdewitte** [comment]
The thing is, having issues is normal in a project. But if I get a complaint from my test users, I first need to understand what the problem is before I can find a way to reproduce and report it. That is a process that takes time. I do not mind spending the time to properly report as long as they are taken care of. I have already mastered your backend to extend it to our application. If I find an issue over there, it is easier for me to submit the patch instead of reporting it. But for the front end, I do not know (yet) how to do it.

The same thing applies to your wiki. I often spot minor issues, but the Wiki repository is not open to accept pull requests. Raising an issue to have something fixed in the wiki is too much of a hassle. 

In this case of this issue, feel free to close it as a duplicate. That is already one issue less on your list.

I will report in the future issues here and put the link on the forum. Seems fine!

**Comment by MartinaeyNL** [comment]
Funny enough it's not a duplicate issue as far as I'm aware. Never posted it as an issue on GitHub myself.

**Comment by DonWillems** [comment]
@MartinaeyNL This issue is still present. Also present on Assets page.

**Comment by Ekhorn** [comment]
Able to reproduce.
